version: "2"

services: 
  db:
    image: postgres
    volumes:
      - postgresql-volume:/var/lib/postgresql/data    
  web:
    build: . 
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/mwdc
    ports: 
      - 3000:3000
    depends_on:
      - db
volumes:
    postgresql-volume:
      external: true      